apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "drip.fullname" . }}-nginx
data:
  nginx.conf: |
      upstream app_server {
        # set fail_timeout to 0 preventing nginx from marking the webapp as unavailable
        server 127.0.0.1:8000 fail_timeout=0;
      }
      server {
        listen 80 default_server;
        client_max_body_size 100M;
        server_name _;
        charset utf-8;
        keepalive_timeout 5;
        location /static/ {
          root /var/www;
        }
        location / {
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_set_header Host $http_host;
          proxy_redirect off;
          proxy_pass http://app_server;
        }
      }